name: Build and Test Python Package

on:
  workflow_call:

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Install UV
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        version: "0.5.27"

    - name: Run tests and generate coverage for Python ${{ matrix.python-version }}
      run: |
        uvx --with .[test] --verbose coverage run -m pytest --junit-xml=result.xml -p no:cacheprovider tests/
        uvx --with coverage[toml] coverage combine
        uvx --with coverage[toml] coverage xml
