name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  unittests:
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit

  check:
    name: All Green
    if: ${{ always() }}
    needs:
      - unittests
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJson(needs) }}
